baseurl         = "https://retasu-blog.netlify.app/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 4
#SectionPagesMenu = "main"
canonifyurls    = true
googleAnalytics = "UA-198136102-1"

[markup]
    [markup.tableOfContents]
        endLevel = 2
        ordered = true
        startLevel = 1

[params]
  title       = "Sawaki's page"
  subtitle    = ""
  copyright   = "© 2021" 

  cover       = "img/blog-cover.jpg"
  description = ""
  metaDescription = ""
  googleAnalytics = ""
  customCSS = ["css/custom-font.css"]
  RSSLink = ""

  twitterName = ""
  fbName = ""
  githubName = "burugaria7"
  # linkedinName = "eueung"
  # mediumName = ""

  #logo = "hugo-logo.png"
  orgName = "Re"
  #orgWebsite = "https://www.telematika.org"
  #orgDescription = "This is Retasu's portfolio"

  showSupport = true

  author = "Sawaki Oku"
  authorAvatar = "img/ghost-icon.png"
  authorLocation = "Bandung, ID"
  authorWebsite = "https://github.com/burugaria7"
  authorDescription = ""

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
   post = "post/:slug"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Go"
  url = "/tags/golang/"
  weight = 100

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = 99

[[menu.main]]
  name = "External"
  url = "https://google.com/"
  weight = 95


